name: Delete packages
description: Delete packages from ghcr.io based on a retention policy
inputs:
  token:
    description: >
      This token will be used to authenticate with the registry.
      If not provided, the action will use GITHUB_TOKEN by default.
    required: false

  package-names:
    description: >
      Comma-separated list of packages to delete
    required: true

  include-tags:
    description: >
      Comma-separated list of tags to consider for deletion
      Supports globbing
    required: false

  exclude-tags:
    description: >
      Comma-separated list of tags to exclude from deletion
      Supports globbing
    required: false

  retention-threshold:
    description: >
      Packages newer than this will not be considered for deletion
    required: true
    example: 2 hours ago UTC

  keep-at-least:
    description: >
      Keep at least this many packages, even if they would otherwise
      be selected for deletion
    required: false
    default: 0

  dry-run:
    description: >
      List packages marked for deletion without removing them
    required: false
    default: false

runs:
  using: node20
  main: index.js
