name: Publish devcontainer
description: Build and publish a devcontainer
inputs:
  image:
    description: Name of the image to build
    required: true
  registry:
    description: 'Docker registry'
    required: false
    default: ghcr.io
  component-name:
    description: Name of the component
    required: false
  github-token:
    description: GitHub token
    required: true
  enable-component-version:
    description: Enable component version
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install gitversion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: 5.12.0

    - name: Determine version number
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2

    - name: Determine component name
      id: component-name
      run: |
        NAME="${{ inputs.component-name }}"
          if [ -z "$NAME" ]; then
            NAME="${{ inputs.image }}"
          fi
          echo "name=${NAME}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Extract component version from devcontainer.json
      id: component-version
      run: |
        DEVCONTAINER_FILE=./src/devcontainers/${{ inputs.image }}/.devcontainer/devcontainer.json
        if [[ -f "$DEVCONTAINER_FILE" ]]; then
          VERSION=$(jq -r '.features | to_entries[0].value.version' $DEVCONTAINER_FILE)
          if [[ "$VERSION" != "null" ]]; then
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "version-found=true" >> $GITHUB_OUTPUT
          else
            echo "Key does not exist in $DEVCONTAINER_FILE."
          fi
        else
          echo "$DEVCONTAINER_FILE does not exist."
        fi
      shell: bash

    - name: Determine image tags using Docker metadata action
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=${{ steps.gitversion.outputs.semVer }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          type=raw,value=${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          type=raw,value=${{ steps.gitversion.outputs.major }},enable=${{ steps.gitversion.outputs.major != '0' && endsWith(github.ref, github.event.repository.default_branch) }}
          type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-{{sha}}
          type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-${{ steps.gitversion.outputs.sha }}
          type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.component-name.outputs.name }}${{ steps.component-version.outputs.version }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) && steps.component-version.outputs.version-found == 'true' }}
          type=raw,value=${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}-${{ steps.component-name.outputs.name }}${{ steps.component-version.outputs.version }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) && steps.component-version.outputs.version-found == 'true' }}
          type=raw,value=${{ steps.gitversion.outputs.major }}-${{ steps.component-name.outputs.name }}${{ steps.component-version.outputs.version }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) && steps.component-version.outputs.version-found == 'true' }}
          type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-{{sha}}-${{ steps.component-name.outputs.name }}${{ steps.component-version.outputs.version }},enable=${{ steps.component-version.outputs.version-found == 'true' }}
          type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-${{ steps.gitversion.outputs.sha }}-${{ steps.component-name.outputs.name }}${{ steps.component-version.outputs.version }},enable=${{ steps.component-version.outputs.version-found == 'true' }}
          type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          type=ref,event=branch
          type=ref,event=pr

    - name: Extract only tag part of full image name
      id: extract-tag-parts
      run: |
        TAGS=$(echo '${{ steps.metadata.outputs.json }}' | jq -r '[.tags[] | split(":") | last] | join(",")')
        echo "$TAGS"
        echo "tags=$TAGS" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set base image tag
      id: set-base-image-tag
      run: |
        FIRST_TAG=$(echo "${{ steps.extract-tag-parts.outputs.tags }}" | cut -d',' -f1)
        find "./src/devcontainers/${{ inputs.image }}" -type f -exec sed -i "s/base:local/base:$FIRST_TAG/g" {} +
      shell: bash

    - name: Authenticate with registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build devcontainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}
        imageTag: ${{ steps.extract-tag-parts.outputs.tags }}
        subFolder: ./src/devcontainers/${{ inputs.image }}
        cacheFrom: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}
