name: Publish devcontainer
description: Build and publish a devcontainer
inputs:
  image:
    description: Name of the image to build
    required: true
  image-tags:
    description: Comma-separated tags to apply to the image
    required: true
  base-image-tag:
    description: Base image tag to use for child image builds
    required: true
  registry:
    description: 'Docker registry'
    required: false
    default: ghcr.io
  component-name:
    description: Name of the component
    required: false
  github-token:
    description: GitHub token
    required: true
  enable-component-version:
    description: Enable component version
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Authenticate with registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build devcontainer
      uses: devcontainers/ci@v0.3
      env:
        BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
      with:
        imageName: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}
        imageTag: ${{ inputs.image-tags }}
        subFolder: ./src/${{ inputs.image }}
        cacheFrom: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}
