name: Publish devcontainers

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  prepare-tags:
    name: Prepare tags
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tags: ${{ steps.extract-tag-parts.outputs.tags }}
      base-image-tag: ${{ steps.set-base-image-tag.outputs.base-image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Set up GitVersion
        uses: gittools/actions/gitversion/setup@bc6623af8fc07d5a8903052dd46da33403eec8e8
        with:
          versionSpec: 6.7.0

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@bc6623af8fc07d5a8903052dd46da33403eec8e8

      - name: Generate image tags
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.gitversion.outputs.semVer }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.major }},enable=${{ steps.gitversion.outputs.major != '0' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-{{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=pr

      - name: Strip image name from tags
        id: extract-tag-parts
        run: |
          TAGS=$(echo '${{ steps.metadata.outputs.json }}' | jq -r '[.tags[] | split(":") | last] | join(",")')
          echo "$TAGS"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Determine base image tag
        id: set-base-image-tag
        run: |
          FIRST_TAG=$(echo "${{ steps.extract-tag-parts.outputs.tags }}" | cut -d',' -f1)
          echo "base-image-tag=$FIRST_TAG" >> $GITHUB_OUTPUT
        shell: bash

  publish-base:
    name: Publish base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - prepare-tags
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base devcontainer image
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5
        with:
          imageName: ghcr.io/${{ github.repository }}/base
          imageTag: ${{ needs.prepare-tags.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
          subFolder: ./src/base
          cacheFrom: ghcr.io/${{ github.repository }}/base

      - name: Export base image for dependent jobs
        if: github.event_name == 'pull_request'
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/base:${{ needs.prepare-tags.outputs.base-image-tag }}"
          docker image inspect "$IMAGE" >/dev/null 2>&1
          docker save "$IMAGE" | gzip > base.tar.gz
        shell: bash

      - name: Upload base image as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: base
          path: base.tar.gz
          if-no-files-found: error
          retention-days: 1

  publish-images:
    name: Publish ${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - prepare-tags
      - publish-base
    strategy:
      fail-fast: false
      matrix:
        image: [dotnet, go, hugo, javascript, python]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish ${{ matrix.image }} devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: ${{ matrix.image }}
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-workflows:
    name: Cleanup workflows
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 5
