name: Publish devcontainers

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  prepare-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.extract-tag-parts.outputs.tags }}
      base-image-tag: ${{ steps.set-base-image-tag.outputs.base-image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@a2825198c355443479ad391aa9d8ba78aa8007ac
        with:
          versionSpec: 5.12.0

      - name: Determine version number
        id: gitversion
        uses: gittools/actions/gitversion/execute@a2825198c355443479ad391aa9d8ba78aa8007ac

      - name: Determine image tags using Docker metadata action
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.gitversion.outputs.semVer }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.major }},enable=${{ steps.gitversion.outputs.major != '0' && endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-{{sha}}
            type=raw,value=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.branchName }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}-${{ steps.gitversion.outputs.sha }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=pr

      - name: Extract only tag part of full image name
        id: extract-tag-parts
        run: |
          TAGS=$(echo '${{ steps.metadata.outputs.json }}' | jq -r '[.tags[] | split(":") | last] | join(",")')
          echo "$TAGS"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Determine base image tag
        id: set-base-image-tag
        run: |
          FIRST_TAG=$(echo "${{ steps.extract-tag-parts.outputs.tags }}" | cut -d',' -f1)
          echo "base-image-tag=$FIRST_TAG" >> $GITHUB_OUTPUT
        shell: bash

  publish-base:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Authenticate with registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/base
          imageTag: ${{ needs.prepare-tags.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
          subFolder: ./src/base
          cacheFrom: ghcr.io/${{ github.repository }}/base

      - name: Save base image for child jobs
        if: github.event_name == 'pull_request'
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/base:${{ needs.prepare-tags.outputs.base-image-tag }}"
          docker image inspect "$IMAGE" >/dev/null 2>&1
          docker save "$IMAGE" | gzip > base.tar.gz
        shell: bash

      - name: Upload base image artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: base
          path: base.tar.gz
          if-no-files-found: error
          retention-days: 1

  publish-dotnet:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
      - publish-base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish dotnet devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: dotnet
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-go:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
      - publish-base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish go devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: go
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-hugo:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
      - publish-base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish hugo devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: hugo
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-javascript:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
      - publish-base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish javascript devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: javascript
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          component-name: node

  publish-python:
    runs-on: ubuntu-latest
    needs:
      - prepare-tags
      - publish-base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish python devcontainer
        uses: ./.github/actions/publish-devcontainer
        with:
          image: python
          image-tags: ${{ needs.prepare-tags.outputs.tags }}
          base-image-tag: ${{ needs.prepare-tags.outputs.base-image-tag }}
          push-image: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-workflows:
      runs-on: ubuntu-latest
      permissions:
        actions: write
        contents: read
      steps:
        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@39f0bbed25d76b34de5594dceab824811479e5de
          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 30
            keep_minimum_runs: 5
